#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""Generate the bounded deterministic placeholder gallery."""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
import sys

import cases


ROOT = Path(__file__).resolve().parent


def text_bytes(value: str) -> bytes:
    return (value.rstrip() + "\n").encode("utf-8")


def json_bytes(value: object) -> bytes:
    return text_bytes(json.dumps(value, indent=2, sort_keys=True))


def placements_tsv() -> bytes:
    lines = ["case_id\tlabel\tx\ty\tz\tblock_state\texpected"]
    lines.extend(
        "\t".join(
            (
                placement.case_id,
                placement.label,
                str(placement.x),
                str(placement.y),
                str(placement.z),
                placement.block_state,
                placement.expected,
            )
        )
        for placement in cases.PLACEMENTS
    )
    return text_bytes("\n".join(lines))


def clear_function() -> bytes:
    minimum_x, minimum_y, minimum_z, maximum_x, maximum_y, maximum_z = (
        cases.ENVELOPE
    )
    return text_bytes(
        "# Generated by gallery/generate.py; do not edit.\n"
        f"fill {minimum_x} {minimum_y} {minimum_z} "
        f"{maximum_x} {maximum_y} {maximum_z} minecraft:air"
    )


def build_function() -> bytes:
    lines = [
        "# Generated by gallery/generate.py; do not edit.",
        f"function {cases.NAMESPACE}:clear",
    ]
    for placement in cases.PLACEMENTS:
        lines.extend(
            (
                f"# {placement.case_id}: {placement.label}",
                f"setblock {placement.x} {placement.y} {placement.z} "
                f"{placement.block_state}",
            )
        )
    lines.append(f"function {cases.NAMESPACE}:verify")
    return text_bytes("\n".join(lines))


def verify_function() -> bytes:
    lines = ["# Generated by gallery/generate.py; do not edit."]
    for placement in cases.PLACEMENTS:
        lines.append(
            f"execute unless block {placement.x} {placement.y} {placement.z} "
            f"{placement.block_state} run tellraw @a "
            f"{{\"text\":\"gallery mismatch: {placement.case_id}\",\"color\":\"red\"}}"
        )
    lines.append(
        "tellraw @a {\"text\":\"XNet placeholder gallery checked\","
        "\"color\":\"yellow\"}"
    )
    return text_bytes("\n".join(lines))


def base_files() -> dict[Path, bytes]:
    function_root = Path(f"datapack/data/{cases.NAMESPACE}/function")
    return {
        Path("placements.tsv"): placements_tsv(),
        Path("datapack/pack.mcmeta"): json_bytes(
            {
                "pack": {
                    "description": "ATM 1.2.0 XNet placeholder gallery",
                    "pack_format": 48,
                }
            }
        ),
        Path("datapack/data/minecraft/tags/function/load.json"): json_bytes(
            {"values": [f"{cases.NAMESPACE}:load"]}
        ),
        function_root / "load.mcfunction": text_bytes(
            "# Generated by gallery/generate.py; do not edit.\n"
            "tellraw @a {\"text\":\"XNet placeholder gallery loaded; "
            f"run /function {cases.NAMESPACE}:build\",\"color\":\"yellow\"}}"
        ),
        function_root / "clear.mcfunction": clear_function(),
        function_root / "build.mcfunction": build_function(),
        function_root / "verify.mcfunction": verify_function(),
        function_root / "release.mcfunction": text_bytes(
            "# Generated by gallery/generate.py; do not edit.\n"
            f"function {cases.NAMESPACE}:clear"
        ),
    }


def generated_files() -> dict[Path, bytes]:
    files = base_files()
    checksum = "".join(
        f"{hashlib.sha256(payload).hexdigest()}  {path.as_posix()}\n"
        for path, payload in sorted(files.items(), key=lambda row: row[0].as_posix())
    )
    files[Path("SHA256SUMS")] = checksum.encode("ascii")
    return files


def write_or_check(check: bool) -> int:
    failures = []
    for relative, payload in generated_files().items():
        destination = ROOT / relative
        if check:
            if not destination.is_file() or destination.read_bytes() != payload:
                failures.append(relative.as_posix())
        else:
            destination.parent.mkdir(parents=True, exist_ok=True)
            destination.write_bytes(payload)
    if failures:
        print(f"generated gallery differs: {', '.join(failures)}", file=sys.stderr)
        return 1
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    return write_or_check(args.check)


if __name__ == "__main__":
    raise SystemExit(main())
