# Generated by gallery/generate.py; do not edit.
function xnet_gallery:clear
# cable-blue-isolated: blue network cable, isolated
setblock 176 100 175 xnet:netcable[color=blue,north=none,south=none,east=none,west=none,up=none,down=none,waterlogged=false]
# cable-red-straight: red network cable, east-west straight
setblock 179 100 175 xnet:netcable[color=red,north=none,south=none,east=cable,west=cable,up=none,down=none,waterlogged=false]
# cable-yellow-corner: yellow network cable, north-east corner
setblock 182 100 175 xnet:netcable[color=yellow,north=cable,south=none,east=cable,west=none,up=none,down=none,waterlogged=false]
# cable-green-t-junction: green network cable, three-way junction
setblock 185 100 175 xnet:netcable[color=green,north=cable,south=none,east=cable,west=cable,up=none,down=none,waterlogged=false]
# cable-routing-cross: routing network cable, horizontal cross
setblock 188 100 175 xnet:netcable[color=routing,north=cable,south=cable,east=cable,west=cable,up=none,down=none,waterlogged=false]
# cable-blue-vertical: blue network cable, vertical straight
setblock 191 100 175 xnet:netcable[color=blue,north=none,south=none,east=none,west=none,up=cable,down=cable,waterlogged=false]
# cable-red-block-ended: red network cable, cable arm and block end
setblock 194 100 175 xnet:netcable[color=red,north=none,south=none,east=block,west=cable,up=none,down=none,waterlogged=false]
# connector-normal: normal green connector with block end
setblock 176 100 178 xnet:connector[color=green,north=block,south=cable,east=none,west=none,up=none,down=none,waterlogged=false]
# connector-advanced: advanced yellow connector with block end
setblock 179 100 178 xnet:advanced_connector[color=yellow,north=none,south=none,east=cable,west=block,up=none,down=none,waterlogged=false]
# facade-bricks: blue facade mimicking bricks
setblock 182 100 178 xnet:facade[color=blue,north=cable,south=cable,east=none,west=none,up=none,down=none,waterlogged=false]{mimic:{Name:"minecraft:bricks"}}
# facade-oak-log-x: routing facade mimicking an east-west oak log
setblock 185 100 178 xnet:facade[color=routing,north=none,south=none,east=cable,west=cable,up=none,down=none,waterlogged=false]{mimic:{Name:"minecraft:oak_log",Properties:{axis:"x"}}}
# controller-error-north: controller error face north
setblock 188 100 178 xnet:controller[error=true,facing=north]
# router-normal-east: router normal face east
setblock 191 100 178 xnet:router[error=false,facing=east]
# wireless-router-normal-west: wireless router normal face west
setblock 194 100 178 xnet:wireless_router[error=false,facing=west]
# redstone-proxy: redstone proxy
setblock 176 100 181 xnet:redstone_proxy
# redstone-proxy-update: redstone proxy update variant
setblock 179 100 181 xnet:redstone_proxy_upd
# antenna-north: antenna face north
setblock 182 100 181 xnet:antenna[facing=north]
# antenna-south: antenna face south
setblock 185 100 181 xnet:antenna[facing=south]
# antenna-base: antenna base
setblock 188 100 181 xnet:antenna_base
# antenna-dish-east: antenna dish face east
setblock 191 100 181 xnet:antenna_dish[facing=east]
# antenna-dish-west: antenna dish face west
setblock 194 100 181 xnet:antenna_dish[facing=west]
# stock-control: stone stock rendering control
setblock 176 100 184 minecraft:stone
function xnet_gallery:verify
