# Generated by gallery/generate.py; do not edit.
execute unless block 176 100 175 xnet:netcable[color=blue,north=none,south=none,east=none,west=none,up=none,down=none,waterlogged=false] run tellraw @a {"text":"gallery mismatch: cable-blue-isolated","color":"red"}
execute unless block 179 100 175 xnet:netcable[color=red,north=none,south=none,east=cable,west=cable,up=none,down=none,waterlogged=false] run tellraw @a {"text":"gallery mismatch: cable-red-straight","color":"red"}
execute unless block 182 100 175 xnet:netcable[color=yellow,north=cable,south=none,east=cable,west=none,up=none,down=none,waterlogged=false] run tellraw @a {"text":"gallery mismatch: cable-yellow-corner","color":"red"}
execute unless block 185 100 175 xnet:netcable[color=green,north=cable,south=none,east=cable,west=cable,up=none,down=none,waterlogged=false] run tellraw @a {"text":"gallery mismatch: cable-green-t-junction","color":"red"}
execute unless block 188 100 175 xnet:netcable[color=routing,north=cable,south=cable,east=cable,west=cable,up=none,down=none,waterlogged=false] run tellraw @a {"text":"gallery mismatch: cable-routing-cross","color":"red"}
execute unless block 191 100 175 xnet:netcable[color=blue,north=none,south=none,east=none,west=none,up=cable,down=cable,waterlogged=false] run tellraw @a {"text":"gallery mismatch: cable-blue-vertical","color":"red"}
execute unless block 194 100 175 xnet:netcable[color=red,north=none,south=none,east=block,west=cable,up=none,down=none,waterlogged=false] run tellraw @a {"text":"gallery mismatch: cable-red-block-ended","color":"red"}
execute unless block 176 100 178 xnet:connector[color=green,north=block,south=cable,east=none,west=none,up=none,down=none,waterlogged=false] run tellraw @a {"text":"gallery mismatch: connector-normal","color":"red"}
execute unless block 179 100 178 xnet:advanced_connector[color=yellow,north=none,south=none,east=cable,west=block,up=none,down=none,waterlogged=false] run tellraw @a {"text":"gallery mismatch: connector-advanced","color":"red"}
execute unless block 182 100 178 xnet:facade[color=blue,north=cable,south=cable,east=none,west=none,up=none,down=none,waterlogged=false]{mimic:{Name:"minecraft:bricks"}} run tellraw @a {"text":"gallery mismatch: facade-bricks","color":"red"}
execute unless block 185 100 178 xnet:facade[color=routing,north=none,south=none,east=cable,west=cable,up=none,down=none,waterlogged=false]{mimic:{Name:"minecraft:oak_log",Properties:{axis:"x"}}} run tellraw @a {"text":"gallery mismatch: facade-oak-log-x","color":"red"}
execute unless block 188 100 178 xnet:controller[error=true,facing=north] run tellraw @a {"text":"gallery mismatch: controller-error-north","color":"red"}
execute unless block 191 100 178 xnet:router[error=false,facing=east] run tellraw @a {"text":"gallery mismatch: router-normal-east","color":"red"}
execute unless block 194 100 178 xnet:wireless_router[error=false,facing=west] run tellraw @a {"text":"gallery mismatch: wireless-router-normal-west","color":"red"}
execute unless block 176 100 181 xnet:redstone_proxy run tellraw @a {"text":"gallery mismatch: redstone-proxy","color":"red"}
execute unless block 179 100 181 xnet:redstone_proxy_upd run tellraw @a {"text":"gallery mismatch: redstone-proxy-update","color":"red"}
execute unless block 182 100 181 xnet:antenna[facing=north] run tellraw @a {"text":"gallery mismatch: antenna-north","color":"red"}
execute unless block 185 100 181 xnet:antenna[facing=south] run tellraw @a {"text":"gallery mismatch: antenna-south","color":"red"}
execute unless block 188 100 181 xnet:antenna_base run tellraw @a {"text":"gallery mismatch: antenna-base","color":"red"}
execute unless block 191 100 181 xnet:antenna_dish[facing=east] run tellraw @a {"text":"gallery mismatch: antenna-dish-east","color":"red"}
execute unless block 194 100 181 xnet:antenna_dish[facing=west] run tellraw @a {"text":"gallery mismatch: antenna-dish-west","color":"red"}
execute unless block 176 100 184 minecraft:stone run tellraw @a {"text":"gallery mismatch: stock-control","color":"red"}
tellraw @a {"text":"XNet visual gallery checked","color":"green"}
